apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-ocp-dev-nginx
  namespace: ss-ocp-dev-nginx
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: "image-registry.openshift-image-registry:5000/ss-ocp-dev-nginx/ss-ocp-dev-nginx"
        name: ss-ocp-dev-nginx
        ports:
        - containerPort: 80